---
title: "DS_Project"
author: "Allison Shafer"
date: "10/27/2019"
output: html_document
---

```{r setup, include=FALSE}

# call in libraries to use

suppressMessages(library(tidyverse))
suppressMessages(library(modelr))
suppressMessages(library(lubridate))
suppressMessages(library(stringr))
suppressMessages(library(purrr))
suppressMessages(library(gganimate))

```


```{r download data}

# set up a data directory if it does not exist already
if(!file.exists("./data")) {dir.create("./data")}

# store urls needed - right click on excel symbol and select 
# copy link address
eviction_US_all <- c("https://eviction-lab-data-downloads.s3.amazonaws.com/US/all.csv")

# check to see if URL saved to variable
eviction_US_all

#download the csv file

download.file(eviction_US_all, destfile = "./data/eviction_US_all.csv", mode = "wb")

# read the csv file into R and save into dataframe

eviction_US_all <- read_csv("./data/eviction_US_all.csv")

eviction_US_all

```

```{r download and load urban/rural classification}

# download and load urbal/rural classifications

# set up a data directory if it does not exist already
if(!file.exists("./data")) {dir.create("./data")}

# store urls needed - right click on excel symbol and select 
# copy link address
urban_rural <- c("http://www2.census.gov/geo/docs/reference/ua/County_Rural_Lookup.xlsx")

#download the .xlsx file

download.file(urban_rural, destfile = "./data/urban_rural.xlsx", mode = "wb")

#read xlsx into R

urban_rural <- read_excel(destfile = "./data/urban_rural.xlsx", mode = "wb")

urbal_rural


```



```{r data exploration}

colnames(eviction_US_all)

head(unique(eviction_US_all$GEOID))
unique(eviction_US_all$)

summary(eviction_US_all)
```