---
title: "DS_Project"
author: "Allison Shafer, Monica Puerto, Alison Ragan"
date: "11/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,out.width = "70%",fig.align = "center",fig.width = 6,fig.asp=.618)

# call in libraries to use

suppressMessages(library(tidyverse))
suppressMessages(library(DataExplorer))
suppressMessages(library(modelr))
suppressMessages(library(lubridate))
suppressMessages(library(stringr))
suppressMessages(library(purrr))
suppressMessages(library(gganimate))
suppressMessages(library(readxl))
#suppressMessages(library(gifski))
suppressMessages(library(tidycensus))
suppressMessages(library(rvest))
suppressMessages(library(tmap))
suppressMessages(library(spData))
suppressMessages(library(tigris))
suppressMessages(library(sf))
suppressMessages(library(gridExtra))
suppressMessages(library(corrplot))
suppressMessages(library(RColorBrewer))

# 11/8: Added packages "tmap", "spData", "tigris"
#install.packages("tmap")
#install.packages("spData")
#install.packages("tigris")

```
# Data Downloads
```{r download data - eviction dataset}

# set up a data directory if it does not exist already
if(!file.exists("./data")) {dir.create("./data")}

# store urls needed - right click on excel symbol and select 
# copy link address
eviction_US_all <- c("https://eviction-lab-data-downloads.s3.amazonaws.com/US/all.csv")

# check to see if URL saved to variable
eviction_US_all

#download the csv file
download.file(eviction_US_all, destfile = "./data/eviction_US_all.csv", mode = "wb") #this takes a bit ranges from 2-5 minutes, over bad WIFI might take 10 min

# read the csv file into R and save into dataframe
eviction_US_all <- read_csv("./data/eviction_US_all.csv")

#replacing "-" in column names 
names(eviction_US_all) <- gsub(x = names(eviction_US_all), pattern = "-", replacement = "_")  
```

```{r import rural urban}

# download and load urbal/rural classifications

# set up a data directory if it does not exist already
if(!file.exists("./data")) {dir.create("./data")}

# store urls needed - right click on excel symbol and select 
# copy link address
urban_rural <- c("http://www2.census.gov/geo/docs/reference/ua/County_Rural_Lookup.xlsx")

#download the .xlsx file

download.file(urban_rural, destfile = "./data/urban_rural.xlsx", mode = "wb")

#read xlsx into R

urban_rural <- read_excel(skip = 3, "./data/urban_rural.xlsx")


# clean data set
urban_rural <- urban_rural %>%
  rename("Percent_Rural" = "2010 Census \r\nPercent Rural",
         "GEOID" = "2015 GEOID") 

# check names were updated
names(urban_rural)

# select only needed fields
urban_rural <-urban_rural %>%
  mutate(rural_flag = ifelse(round(Percent_Rural, 3) > 50, 1, 0)) %>%
  select(GEOID, State, Percent_Rural, rural_flag) 

# view cleaned up dataset
urban_rural
```

```{r Webscrape US Labor Stats}
if(!file.exists("./data/labor_data")) {dir.create("./data/labor_data")}

#save url into a variable
url <- "https://www.bls.gov/lau/#tables"

#download the html content using read_html
download.file(url,destfile="./data/uslabor.html")
us_county_labor_html <- read_html("./data/uslabor.html")

#extract the xslx 
us_county_labor_html %>% 
   rvest::html_nodes("ul") %>%
        rvest::html_nodes("li") %>%
        rvest::html_nodes("a") %>%
        rvest::html_attr("href") %>%
        str_subset(".xlsx$") -> us_labor_urls

#domain
domain <- "https://www.bls.gov"

#paste domain to urls
str_c(domain,us_labor_urls) -> us_labor_urls

#only need years from 2000 to 2016
us_labor_urls[3:19] -> us_labor_2000_2016
years <- rep(2000:2016,1)

#a for loop that downloads each file
for(i in seq_along(us_labor_2000_2016)){
  download.file(us_labor_2000_2016[i],destfile = paste("./data/labor_data/",years[i],".xslx",sep=""),mode="wb")
}

#save the files pertaining to us labor
labor_files <- dir("./data/labor_data")


#create a function that downloads each url and saves it #into a dataframe
read_files <- function(x){
read_excel(path= paste("./data/labor_data/",x,sep=""),skip = 7,col_names = c("laus_code","state_fips_code","county_fips_code","county_name","year","","labor_force","employed","unemployed","unemployment_rate"),sheet = 1,na="")
}

#map the function to read each file 
map(labor_files,read_files) -> all_labor_data

#join all the US labor tables
all_labor_data %>% reduce(full_join) -> all_labor_data
```
# Data Cleaning
``` {r clean up data set}
#remove some rows that have NA in Year and remove empty column next to year
filter(all_labor_data,!is.na(year)) %>% select(-6) -> all_labor_data
 
 
#creating a GEOID to join 
all_labor_data$GEOID <- str_c(all_labor_data$state_fips_code,all_labor_data$county_fips_code)
 
 
#change year to integer
all_labor_data$year <- as.integer(all_labor_data$year)
 
```

# Downloading Spatial Dataset

```{r download county spatial data}

# set up a data directory if it does not exist already
if(!file.exists("./data")) {dir.create("./data")}

#download county shapefiles
download.file("https://www2.census.gov/geo/tiger/GENZ2018/shp/cb_2018_us_county_500k.zip", destfile = "./data/county_shp.zip")

spatial_data <- "./data/county_shp.zip"

unzip(spatial_data, overwrite = TRUE, exdir = "./data/spatial/county_shp")

county_boundaries <- st_read("./data/spatial/county_shp/cb_2018_us_county_500k.shp")
county_boundaries

```
# Creating Additional Datasets From Existing Data

```{r make county dataset}
#County Table joined with 2 additional variables : rural flag and unemployment rate

eviction_county <- eviction_US_all %>%
  right_join(urban_rural, key = "GEOID") %>% 
  left_join(select(all_labor_data,GEOID,year,unemployment_rate), by =c("GEOID" = "GEOID", "year"="year"))
         
eviction_county 

```

```{r make state dataset}

eviction_state <- eviction_US_all %>%
  filter(nchar(GEOID) == 2)
         
eviction_state

```

```{r make region column}
states_regions <- as.data.frame(cbind("states"= state.name,"region"=state.region))#creating state and region table

#recode regions
region_names <- c("1" = "Northeast", "2" = "South", "3" = "North Central","4"="West")
recode(states_regions$region, !!!region_names) -> states_regions$region
  
left_join(eviction_state, states_regions, by = c("name"="states")) -> eviction_state

left_join(eviction_county, states_regions,by = c("parent_location"="states")) -> eviction_county

#Need to replace DC with a region
eviction_county$region[eviction_county$name == "District of Columbia"] <- "Northeast"

#remove rows with no region

```

```{r make pct_non_white column for county}
eviction_county$pct_nonwhite <- 100 - eviction_county$pct_white
```


# Data Exploration


```{r Chunk Nulls Exploration}
#We have 22.5% missing of eviction rate data in county and 11% missing in state. ALl 
plot_missing(eviction_state,title = "Missing Data in Eviction States Table",ggtheme = theme_minimal(),list(Good = 0.02, OK = 0.1, Bad = 0.2,Remove=.3))
plot_missing(eviction_county,title = "Missing Data in Eviction County Table",ggtheme = theme_minimal(),list(Good = 0.02, OK = 0.1, Bad = 0.2,Remove=.3))

```


```{r Check if any states missing Evictions}
eviction_state %>% group_by(GEOID,name) %>% summarise_at(c("eviction_filings", "evictions"), sum, na.rm = TRUE) %>% filter(evictions == 0) -> null_states
grid.arrange(tableGrob(null_states))
```


```{r Check %pct counties with complete eviction filing by year}
select(eviction_county,GEOID,year,eviction_filing_rate) %>% 
  filter(!is.na(GEOID)) %>%
  pivot_wider(names_from=year,values_from = eviction_filing_rate) -> pivot_wider_years

data.frame("pct_eviction_rate_null" = colSums(is.na(pivot_wider_years))/3146)-> years_null
rownames_to_column(years_null,var="year") -> years_null
subset(years_null,pct_eviction_rate_null != 0) %>%
  subset(pct_eviction_rate_null != 1) %>%
  ggplot(aes(year,pct_eviction_rate_null)) +
  geom_bar(stat = "identity",fill=spectral[1]) +
  theme_classic() +
  ggtitle("Percent of Counties with Null Eviction Filing Rate by Year")


```



```{r Correlation Matrix}

#plot_correlation(na.omit(eviction_county), maxcat = 5L)
na.omit(eviction_county) %>%
filter(year>2009) %>%
mutate(GEOID = as.numeric(GEOID)) %>%
select_if(is.numeric) %>%
group_by(GEOID) %>%
  summarise_all(mean,na.rm=TRUE) %>% 
  as.matrix() %>% cor()  -> cor_matrix

#corrplot1

corrplot(cor_matrix[,1:nrow(cor_matrix)][1:nrow(cor_matrix),21, drop=FALSE], cl.pos='n',cl.ratio = .2, method = "number", tl.srt = 45,tl.col = "black",col = spectral[1:4],tl.cex = .8)

#corrplot 2
corrplot(cor_matrix, type="upper", order="hclust", sig.level = 0.01, insig = "blank",tl.srt = 45,tl.col = "black",cl.ratio = .2,tl.cex = .4)

#corrplot 3
ggcorrplot(cor_matrix[,1:nrow(cor_matrix)][1:nrow(cor_matrix),21, drop=FALSE], sig.level=0.05, lab_size = 4.5, p.mat = NULL, 
           insig = c("pch", "blank"), pch = 1, pch.col = "black", pch.cex =1,
           tl.cex = 8) +
  theme(axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) 
```



```{r data exploration, echo = false, eval = false}

#look at col names
colnames(eviction_US_all)

#look at summary of data
summary(eviction_US_all)

summary(all_labor_data)

```

```{r EDA county - eviction rate}

# get top 100 counties with highest average evistion rate
eviction_county %>%
  group_by(GEOID) %>%
  summarise(
    avg_rate = mean(eviction_filing_rate, na.rm = TRUE)
  ) %>%
  top_n(100) %>%
  arrange(desc(avg_rate))


# histogram of eviction rates in county dataset
eviction_county %>%
  filter(year >2009) %>%
  group_by(eviction_filing_rate) %>%
  count() %>%
  ggplot(aes(eviction_filing_rate)) +
  geom_histogram(bins = 50,fill=spectral[4]) +
  #scale_x_continuous(limits=c(0,90)) +
  theme_minimal() +
  scale_x_continuous(breaks=seq(0,200,5)) +
  ggtitle("Distribution of Average Eviction Filing Rate 2010-2016") +
  ylab("Count of Counties") +
  xlab("Average Eviction Filing Rate per County") +
  geom_vline(aes(xintercept=3.17),
               linetype="dashed", size=1)


```



```{r Distribution of Variables}
eviction_county %>%
  filter(year>2009) %>%
  select(-year,-eviction_filings, -evictions,-imputed, -low_flag,-subbed) %>% 
  mutate(GEOID = as.numeric(GEOID)) %>%
  keep(is.numeric) %>%
  group_by(GEOID) %>%
  # Keep only numeric columns
  summarise_all(mean,na.rm=TRUE) %>%
  gather() %>%                             # Convert to key-value pairs
  ggplot(aes(value)) +                     # Plot the values
    facet_wrap(~ key, scales = "free") +   # In separate panels
    geom_density(fill=spectral[1]) +
  theme_minimal() +
  ggtitle("Distribution of Variables Eviction Data 2010-2016")
  
```



```{r EDA state level data}

# look at dataset

names(eviction_state)

summary(eviction_state)

# look at 2016 
eviction_state %>%
  filter(year == 2016) %>%
  ggplot(aes(x = name, y = `poverty-rate`)) +
  geom_bar(stat = 'identity') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip()

```

```{r EDA county level data}

# look at data set
eviction_county %>%
  group_by(GEOID) %

ncol(eviction_county)
summary(eviction_county)
glimpse(eviction_county)

```

```{r gganimate eviction for state}

# look at eviction rate over time per state -- create gganimate
# this needs to have better formatting for final.

eviction_state %>%
  ggplot(aes(x = eviction_filing_rate, y = name)) +
  geom_point(aes(size = population, fill = rent_burden),
             shape = 21) +
  scale_x_log10(breaks = 2^(-1:7)*1000) +
  scale_size(range = c(1, 20), guide = FALSE) +
  labs(x = "Eviction Rate",
       y = "State") +
  transition_states(year, transition_length = 1,
                    state_length = 1)+
  ggtitle("Year showing {closest_state}",
          subtitle = "Frame {frame} of {nframes}")+
  theme_bw()
```

# Set up Spatial Datasets for Mapping
```{r set up spatial datasets}

# get Census TIGER shapefiles for state
state_us_geo <- tigris::states(class= "sf")


# add spatial data to the state level eviction data
eviction_by_state <- eviction_state %>%
                      left_join(us_geo, c("GEOID" = "GEOID"))

eviction_by_state

# add spatial data to the county level eviction data
eviction_by_county <- eviction_county %>%
                      left_join(county_boundaries, c("GEOID" = "GEOID"))

eviction_by_county
```



```{r Region Trend Eviction Filing Rate}

select(eviction_county, region,eviction_filing_rate, year) %>%
  filter(year>2009) %>%
  group_by(year,region) %>%
  summarise_all(mean,na.rm=TRUE) %>%
  ggplot(aes(year,eviction_filing_rate,fill = region)) +
  geom_line() + 
  scale_x_continuous(breaks=seq(2009,2016,1)) + 
  theme_minimal() + 
  ggtitle("Average Regional Eviction Filing Rate by year") +
  scale_color_brewer(palette = "Spectral")

select(eviction_county, region,eviction_filing_rate, year) %>%
  filter(year > 2009) %>%
  na.omit() %>%
  mutate(year_bin = ifelse(year > 2008,"y2008_2016","y2000_2008")) %>%
  select(region,year_bin, eviction_filing_rate) %>%
  group_by(region,year_bin) %>%
  summarise_all(mean,na.rm=TRUE) %>%
  pivot_wider(names_from = "year_bin",values_from = "eviction_filing_rate") %>%
  mutate(delta = y2008_2016 - y2000_2008) %>%
  ggplot(aes(region,delta)) +
  geom_bar(stat="identity") +
  theme_minimal()
  #scale_fill_brewer(palette = "Set3")
  
```



```{r pct change metric}
#pct_change metric
select(eviction_county, year, GEOID,population,eviction_filing_rate) %>%
  group_by(GEOID,population) %>% 
  slice(which.min(year)) %>%
  group_by(GEOID) %>%
  arrange(desc(year), .by_group = TRUE) %>%
  mutate(pct_pop_change = (population/lead(population) - 1) * 100) -> pct_pop_change_county



#create scales for data
#x_scale <- scale_x_continuous(limits = c(0,4))
#y_scale <- scale_y_continuous(limits = c(0,4))


#join region
left_join(pct_pop_change_county,eviction_county, by ="GEOID") %>%
  filter(year.x > 2004) %>%
  select(year.x,pct_pop_change,eviction_filing_rate.x,region) %>%
ggplot(aes(pct_pop_change,eviction_filing_rate.x,color=region)) +
  geom_point() +
  geom_jitter() +
  x_scale +
  y_scale + 
  facet_wrap(~year.x) + theme_minimal() + scale_color_brewer(palette = "Spectral")
+ ggtitle("Percent Population Change by Census Release Data ")

```



```{r pct change bar graph top 50 counties}
left_join(pct_pop_change_county,eviction_county_2010, by ="GEOID") %>%
  #filter(year.y > 2009) %>%
  dplyr::select(pct_pop_change,eviction_filing_rate,region,name) %>%
  group_by(region,name) %>%
  summarise_all(mean,na.rm=TRUE) %>%
  arrange(desc(eviction_filing_rate.x)) %>%
  head(50) %>%
  ggplot(aes(name,pct_pop_change,color=region.x,fill=region.x)) +
  geom_bar(stat="identity") + 
  theme_minimal() +
  scale_fill_brewer(palette = "Spectral")
```




```{r}
dplyr::select(eviction_county_2010, parent_location,eviction_filing_rate, year,region) %>%
  filter(year > 2010) %>% #have to have even amount of years
  na.omit() %>%
  mutate(year_bin = ifelse(year > 2014,"y2014_2016","y2011_2013")) %>%
  dplyr::select(parent_location,year_bin, eviction_filing_rate,region) %>%
  group_by(parent_location,year_bin,region) %>%
  summarise_all(mean,na.rm=TRUE) %>%
  pivot_wider(names_from = "year_bin",values_from = "eviction_filing_rate") %>%
  mutate(delta = y2014_2016 - y2011_2013) %>%
  ggplot(aes(parent_location,delta,fill=region)) +
  geom_bar(stat="identity") +
  theme_minimal() +
  scale_color_brewer(palette = "Spectral") +
  ggtitle("Average Eviction Delta of 2014-2016 vs 2011-2013")
```

